### ISSUE TITLE
Empty due date still showing section

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#296]
On listings where there is no due date, the "empty due date" section is still showing.

Ex.
[Alameda Listing](https://dev.housingbayarea.mtc.ca.gov/listing/ext/13ba9bcc-feb1-49d3-b3ab-55996b20ed7d)
![image.png](https://images.zenhubusercontent.com/637d0ad803d649bd438df415/302aaa3b-42ee-4eaa-bc70-f557dca9d7fe)

AC:
When there is not a due date on a listing, the grey box should not show.

**Comment by emilyjablonski** [comment]
We should have two listing states - first come first serve, and lottery / application due date - the blue box at the bottom of every listing card should either say "first come first serve" or the due date. If you look on [Alameda staging](https://ala.bloom.exygy.dev/listings) we can see a bug where sometimes the box is empty. The cause of this looks to be that when users answer the question `How is the application review order determined?` as lottery, a due date does not then become required, so a listing is in that lottery state without a due date to show. We're not sure how to make the due date required in response from a UX perspective since the questions on the page are just located far apart (cc @eajensenwa )

**Comment by sarahlazarich** [comment]
Spoke with @eajensenwa on this -- for the sake of fixing this bug, lets remove the box where there's no due date for now. We're going to open a separate ticket to reevaluate the UX of filling out a listing in general.

**Comment by sarahlazarich** [comment]
This may require a UIC change -- may need an extra step to pull this over to doorway from core if it is.

**Comment by sarahlazarich** [comment]
moved to core, closing
