### ISSUE TITLE
Mobile Form Fields

### ISSUE THREAD

**Issue by sarahlazarich** [metrotranscom/doorway#690]
Bug: 

- On mobile, when moving through the application, Clicking into the form fields zooms in and makes it difficult to navigate to a new page

Expected Behavior: 

- On mobile, form fields should keep their sizing.

**Comment by sarahlazarich** [comment]
Won't be able to use mobile emulator to test, will need to use a device

**Comment by jaredcwhite** [comment]
Will implement a fix for this in Core first, then pull over.

**Comment by jaredcwhite** [comment]
This actually seems to be a Doorway-specific issue because the font size of input controls is a little too small. By bumping the size up to the body font size, that automatic zoom issue goes away. It does mean the visual appearance changes slightly. Before/after (look at city name & state):

<img src="https://github.com/metrotranscom/doorway/assets/658496/1b141a71-f7ec-46d2-982d-9e3eabc0b055" width="453">

<img src="https://github.com/metrotranscom/doorway/assets/658496/4a554219-b8fd-41c2-9108-d5b46385bdc6" width="450">

I guess it's a question for the design team @slowbot if this would be an acceptable change.

**Comment by sarahlazarich** [comment]
this was released
